<!DOCTYPE html>
<html lang="en-US">
<head>
    <?= $this->meta->head($category); ?>
</head>
<body>
    
    <h1><?= $category->name ?></h1>
    <time><?= $category->created->format('M d, Y') ?></time>
    
    <article><?= $category->about ?></article>
    
    <?php if($posts): ?>
        <ol>
            <?php foreach($posts as $post): ?>
            <li><a href="<?= $post->page ?>"><?= $post->title ?></a></li>
            <?php endforeach; ?>
        </ol>
    <?php endif; ?>
    
    <?php if($pagination): ?>
        <ul>
            <?php foreach($pagination as $label => $link): ?>
            <li><a href="<?= $link ?>"><?= $label ?></a></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    
    <?= $this->meta->foot($category); ?>
</body>
</html>